name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libffi-dev \
          distutils \
          python3-setuptools \
          git \
          zip \
          unzip \
          openjdk-17-jdk

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install "cython<3.0.0" buildozer

    - name: Generate Spec File
      run: buildozer init

    - name: Configure Spec File
      shell: python
      run: |
           f = open('buildozer.spec', 'r')
           data = f.read()
           f.close()
  
           lines = data.split('\n')
           for i, line in enumerate(lines):
               if line.startswith('requirements ='):
                   lines[i] = (
                       'requirements = python3, kivy, '
                       'pyjnius, flask, requests'
                   )
               elif line.startswith('#android.permissions ='):
                   lines[i] = (
                       'android.permissions = INTERNET, '
                       'READ_EXTERNAL_STORAGE, '
                       'WRITE_EXTERNAL_STORAGE, '
                       'MANAGE_EXTERNAL_STORAGE'
                   )
               elif line.startswith('#android.api ='):
                   lines[i] = 'android.api = 33'
  
           data = '\n'.join(lines)
           f = open('buildozer.spec', 'w')
           f.write(data)
           f.close()

    - name: Build APK with Buildozer
      run: buildozer android debug
      env:
        ACCEPT_SDK_LICENSE: "y"

    - name: Upload Finished APK
      uses: actions/upload-artifact@v4
      with:
        name: Jarvis-Android-APK
        path: bin/*.apk
